### ISSUE TITLE
luajit examples/simple.lua not works

### ISSUE THREAD

**Issue by zhaozg** [javalikescript/lua-webview#6]
luajit examples/simple.lua not works on MacOS with COCOA, just show a blank windows.

maybe context pass by https://github.com/javalikescript/lua-webview/blob/master/examples/simple.lua#L30 not work.

![image](https://user-images.githubusercontent.com/542599/153812617-74674167-3826-4ea3-a352-3fcdbefd436e.png)

Anyone meet this?

**Comment by javalikescript** [comment]
Hello,

Thank you for submitting the issue and also providing a Pull Request on the webview C library.
I do not have a MacOS development environment that's why I never supported MacOS for lua-webview.
As you probably guessed the originating library had a much broader scope that I am not interested to support despite that I kept the code.
I will update the webview C library readme to clarify this point.

Have a good day,
Samuel

**Comment by zhaozg** [comment]
Thank you for nice work. I found the reason, more strict URL encode works for cocoa, and  a simple PR can solve this. I will make a PR after somedays.
